# Fiebre de Norsilk

In [1]:
import numpy as np

# Crear una matriz cuadrada de números aleatorios
np.random.seed(42)  # Para reproducibilidad
matrix = np.random.rand(3, 3)  # Matriz 3x3 con valores entre 0 y 1

# Calcular la inversa de la matriz si es invertible
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Matriz inversa:")
    print(inverse_matrix)
else:
    print("La matriz no es invertible")

# Calcular estadísticas básicas
mean_value = np.mean(matrix)
std_dev = np.std(matrix)
max_value = np.max(matrix)
min_value = np.min(matrix)

print("\nMatriz original:")
print(matrix)
print(f"\nMedia: {mean_value}")
print(f"Desviación estándar: {std_dev}")
print(f"Valor máximo: {max_value}")
print(f"Valor mínimo: {min_value}")


Matriz inversa:
[[ -1.72626243   2.61222492   1.42422141]
 [-14.65094529   7.62717264  15.86153376]
 [ 21.2780693  -11.24277772 -21.32970539]]

Matriz original:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Media: 0.4992549757478559
Desviación estándar: 0.30888608340705315
Valor máximo: 0.9507143064099162
Valor mínimo: 0.05808361216819946
